---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - ../../vars/external_vars.yml

  tasks:
    - name: vault token check
      fail:
        msg: "vault token was not set for {{ hashi_vault_addr }}"
      when: hashi_vault_token | length == 0

    - name: Install imperva role
      include_role:
        name: os_sectools/imperva
      tags:
        - always
